name: testC
on: [push, pull_request]
env:
  nim-version: 'stable'
jobs:
  build:
    runs-on: ubuntu-latest
    if: ! contains(github.event.head_commit.message, '[skip ci]')
    steps:
    - uses: actions/checkout@v2
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v2
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ env.nim-version }}
    - name: Test C backend
      run: nimble testC

